# Generated by Django 2.2.2 on 2024-06-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20240626_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='职位')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department', verbose_name='所属部门')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=64, verbose_name='省份')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('district', models.CharField(max_length=64, verbose_name='区县')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Position', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Residence', verbose_name='户口所在地'),
        ),
    ]
