# Generated by Django 2.2.2 on 2024-06-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20240628_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='district',
        ),
    ]
