# Generated by Django 2.2.2 on 2024-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_residence_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('CP', '中共党员'), ('CY', '共青团员'), ('LX', '群众'), ('QT', '其他')], default='LX', max_length=2, verbose_name='政治面貌'),
        ),
    ]
