# Generated by Django 2.2.2 on 2024-06-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary',
            field=models.FloatField(default=0.0, verbose_name='固定薪资'),
        ),
    ]
