# Generated by Django 2.2.2 on 2024-06-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20240629_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='status',
            field=models.CharField(choices=[('ON_DUTY', '在岗'), ('ON_LEAVE', '请假'), ('ABSENT', '旷工'), ('ON_BUSINESS', '出差')], default='ON_DUTY', max_length=32, verbose_name='考勤状态'),
        ),
    ]
