# Generated by Django 2.2.2 on 2024-06-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20240629_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='address',
        ),
        migrations.AddField(
            model_name='book',
            name='address_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='户口所在地ID'),
        ),
    ]
